"""Generate `fixtures/volume.sql` — enough local cards to reach page 4.

**This is a second corpus, and that is the point.** `fixtures.sql` is selected by
*coverage*: 34 cards chosen so every enum member and every structural edge case appears at
least once. It is deliberately small, it is the golden-file corpus for the `localize()`
parity test, and roughly a hundred assertions across `smoke.sh` and the Python tests are
written against its exact totals. Growing it to reach a second page would have meant
rewriting all of that and multiplying 1.6 MB of golden files by twenty, to test something
none of those tests are about.

So volume is kept apart from coverage. This file adds *bulk* — cards that exist only to be
the 200th, the 400th and the 600th row of a result set.

**What it is for.** `pageSize` is 200 (`CardListViewAPI.vue`), and the fixture corpus is 34
cards, so locally:

    hasMore = cards.length < total  ->  34 < 34  ->  false

`loadMore` can therefore never fire against fixtures, and neither can anything downstream
of it: infinite scroll, the append path, `skip_count`, or the scroll restore that runs when
you return from a card. That whole region of the app was unreachable locally and only
observable in production, which is where #59 was found for the third time — as a truncation
that silently undid a scroll restore once the list was more than one page deep.

Four pages rather than two, because the interesting cases are not at the first boundary:
returning from a card on page 3 is what distinguishes "the offset was restored" from "the
list was truncated back to page 1 and the browser re-clamped the offset".

**Translations are trimmed.** Q&A items and the `extra` block are dropped from every card
here — they are roughly half the bytes and none of the point, since coverage for both
already lives in `fixtures.sql` (546 Q&A items across 34 cards). That keeps this at ~2 MB
rather than ~4 MB for the same number of rows. A volume card still carries its name, its
arts and its ability text in all seven locales, so search and the filters behave normally.

Loaded *after* `fixtures.sql` and never instead of it:

    npx wrangler d1 execute hololive-ocg-wiki-db --local --file=fixtures/fixtures.sql
    npx wrangler d1 execute hololive-ocg-wiki-db --local --file=fixtures/volume.sql

⚠️ **`smoke.sh` deliberately does not load this.** Its assertions are written against the
34-card corpus (`d['total'] == 34`, `d['total'] == 6`, and so on), and they are about the
query shapes rather than about volume. Loading this there would break them all for no gain.
`make dev` loads both, because that is where a human clicks through infinite scroll.

Regenerated by `make volume`, which needs `holo-data build` output — the same source and
the same gitignored-input caveat as `make fixtures`. The output is committed, so a fresh
clone needs no Python toolchain (D12).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from holo_schema import CardCollection

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "pipeline" / "src"))

from holo_data import seed as seed_module  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_fixtures_sql import quote  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[3]
FIXTURES_DIR = REPO_ROOT / "fixtures"

# Enough to put the fourth page in reach at `pageSize` 200, counting the 34 coverage
# fixtures that load alongside these. The exact number is not load-bearing; being
# comfortably past 3 × 200 is.
VOLUME_CARDS = 620

# Matches `generate_fixtures_sql.py`: a real clock would make every regeneration show
# every row as changed.
SEEDED_AT = "1970-01-01T00:00:00Z"

BANNER = """-- DO NOT EDIT — generated from `holo-data build` output by
-- packages/schema/scripts/generate_volume_sql.py.
-- Regenerate with `make volume`; `make check` fails if this file is stale.
--
-- Bulk cards, so local development can reach page 4 (#59). `pageSize` is 200 and the
-- coverage corpus is 34 cards, so without these `hasMore` is always false locally and
-- infinite scroll, the append path and the scroll restore are all unreachable.
--
-- Load AFTER fixtures.sql, never instead of it:
--
--   npx wrangler d1 execute hololive-ocg-wiki-db --local --file=fixtures/fixtures.sql
--   npx wrangler d1 execute hololive-ocg-wiki-db --local --file=fixtures/volume.sql
--
-- These are for *volume*, not coverage — fixtures.sql owns every enum and every edge
-- case, and smoke.sh's totals are written against those 34 cards alone. Q&A items and
-- the `extra` block are trimmed here; fixtures.sql covers both.
"""


def _trim(card: dict[str, Any]) -> dict[str, Any]:
    """Drop the two heaviest translation blocks.

    Roughly half the bytes of a typical card, and neither is what this corpus is for:
    `fixtures.sql` carries 546 Q&A items across its 34 cards, which is where the Q&A
    endpoint and the `extra` rendering are actually covered. Name, arts and ability text
    are kept so search and the filters behave normally over these rows.
    """
    card = dict(card)
    translations = {}
    for locale, payload in (card.get("translations") or {}).items():
        payload = dict(payload)
        payload.pop("qa_items", None)
        payload.pop("extra", None)
        translations[locale] = payload
    card["translations"] = translations
    return card


def _source() -> Path:
    from holo_data import paths

    return paths.cards_json()


def select(raw: dict[str, Any]) -> CardCollection:
    """The first `VOLUME_CARDS` cards that are not already coverage fixtures.

    In id order, and skipping anything in `card-ids.txt`: loading a card that
    `fixtures.sql` already inserted would violate the primary key and abort the script.
    Deterministic, so regenerating on unchanged input produces an identical file.
    """
    fixture_ids = {
        line.split()[0]
        for line in (FIXTURES_DIR / "card-ids.txt").read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }

    volume = [
        _trim(card)
        for card in sorted(raw["cards"], key=lambda c: int(c["id"]))
        if card["id"] not in fixture_ids
    ][:VOLUME_CARDS]

    return CardCollection.model_validate(
        # A fixed timestamp, for the same reason `build_fixtures.py` uses one.
        {"generated_at": "2026-07-25T00:00:00Z", "cards": volume}
    )


def statements(collection: CardCollection) -> list[str]:
    lines: list[str] = []
    columns = ", ".join(
        [
            *seed_module.CARD_COLUMNS,
            "payload",
            "qa_payload",
            "content_hash",
            "qa_hash",
            "seeded_at",
        ]
    )

    for card in collection.cards:
        row = seed_module.to_row(card)
        values = ", ".join(
            quote(value)
            for value in (
                *row.columns,
                row.payload,
                row.qa_payload,
                row.content_hash,
                row.qa_hash,
                SEEDED_AT,
            )
        )
        lines.append(f"INSERT INTO cards ({columns}) VALUES ({values});")

        for _field, table, value_column in seed_module.JUNCTIONS:
            for entry in row.junction_values.get(table, []):
                lines.append(
                    f"INSERT INTO {table} ({value_column}, card_id) "
                    f"VALUES ({quote(entry)}, {quote(row.id)});"
                )

        lines.append(
            "INSERT INTO cards_fts (rowid, card_number, text, qa) VALUES "
            f"({seed_module.rowid_for(row.id)}, {quote(row.columns[1])}, "
            f"{quote(row.search_text)}, {quote(row.qa_text)});"
        )

    return lines


def render(source: Path) -> str:
    raw = json.loads(source.read_text(encoding="utf-8"))
    collection = select(raw)

    # No DELETE preamble, unlike fixtures.sql: this file *adds* to what that one loaded,
    # and clearing the tables here would drop the coverage corpus on the floor. Re-running
    # it is therefore not idempotent — `db:local` reapplies schema.sql first, which is
    # what makes the pair as a whole safe to repeat.
    return "\n".join([BANNER, *statements(collection), ""])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the output is stale")
    parser.add_argument("--source", type=Path, default=None)
    args = parser.parse_args()

    target = FIXTURES_DIR / "volume.sql"

    source = args.source or _source()
    if not source.exists():
        if args.check:
            # The source is gitignored working state, so a fresh clone cannot regenerate.
            # The committed file is what matters there, and `test_volume.py` asserts its
            # invariants without needing the source — same arrangement as the fixtures.
            print("✓ volume.sql (source unavailable, skipping staleness check)")
            return 0
        print(f"source not found: {source}", file=sys.stderr)
        print("Run `holo-data transform && holo-data build` first.", file=sys.stderr)
        return 1

    content = render(source)

    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            print("Generated SQL is out of date:", file=sys.stderr)
            print(f"  {target.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("\nRun `make volume` and commit the result.", file=sys.stderr)
            return 1
        print("✓ volume.sql is current")
        return 0

    target.write_text(content, encoding="utf-8", newline="")
    size_mb = target.stat().st_size / 1024 / 1024
    print(f"  wrote {target.relative_to(REPO_ROOT)} ({size_mb:.1f} MB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
