#!/usr/bin/env bash
# Populate the local R2 bucket with the three artifacts the site reads (D12).
#
# `wrangler d1 execute --local` gives us a database from `fixtures.sql`, but nothing
# equivalent existed for R2 — so `make dev` served a site whose filter dropdowns 404ed in
# six of seven locales and whose about dialog had no content. The endpoints were right;
# the local bucket was simply empty.
#
# What goes in:
#   filter-options/{locale}.json   fixtures/artifacts/ — generated from the 34 cards
#   status.json                    fixtures/artifacts/ — a synthesised seeder report
#   info.json                      content/ — the real committed editorial copy
#
# **Everything uploaded here is committed**, so this needs `wrangler` and nothing else.
# It used to generate the artifacts on the fly with Python, which put `uv sync`, a venv
# and pydantic between a fresh clone and a working site. `fixtures/artifacts/` is
# regenerated by `make generate` and its staleness is caught by `make check` — the same
# rule ADR 0001 applies to the contract's TypeScript.
#
# Production gets these from `holo-data build` + `publish` + `seed`.
set -euo pipefail

cd "$(dirname "$0")/.."

BUCKET=hololive-ocg-wiki-artifacts
ARTIFACTS=../../fixtures/artifacts

if [[ ! -d "$ARTIFACTS/filter-options" ]]; then
  echo "✗ $ARTIFACTS/filter-options is missing — run 'make generate'" >&2
  exit 1
fi

for file in "$ARTIFACTS"/filter-options/*.json; do
  npx wrangler r2 object put "$BUCKET/filter-options/$(basename "$file")" \
    --local --file="$file" >/dev/null
done
npx wrangler r2 object put "$BUCKET/status.json" --local --file="$ARTIFACTS/status.json" >/dev/null
npx wrangler r2 object put "$BUCKET/info.json" --local --file=../../content/info.json >/dev/null

echo "✓ local R2 seeded — 7 filter-options, info.json, status.json"
